### ISSUE TITLE
TRNdat not found

### ISSUE THREAD

**Issue by noelleje** [davidjpmoore/HiPk2013#11]
@davidjpmoore this data frame does not exist for me and I recently pulled from git so I should be current. No terrain excel file exists for me if that is what the data frame is from..

**Comment by davidjpmoore** [comment]
@noelleje apologies ... been driving for a few days. The terrain data comes from @rlybrand4 and I have a working copy. I can put it on git and you can grab it.

**Comment by davidjpmoore** [comment]
@noelleje please download the file from iPlant 
It's in MASTERDATA/Final_Terrain4715.txt
Store the file in your data folder and then run the input script to get the TRNdat dataframe 
TRNdat = read.table("data/Final_Terrain4715.txt", sep="\t", header=TRUE)

@rlybrand4 I saw that an update of these data was on your todo list. That's great - when you get them sorted could you prepare a README file and let @noelleje know so that we all have a current version of the files?

**Comment by rlybrand4** [comment]
Yes, this should be updated (and uploaded) by early next week. I have generated updated values for total solar radiation and TWI. I will let Noelle know once this is available.

**Comment by davidjpmoore** [comment]
@noelleje @rgallery 
new terrain spreadsheet and the accompanying ReadMe file to iPlant: 

MASTERDATA/HighPark_Terrain_Master_82415
MASTERDATA/HighPark_Terrain_Master_README_82415

I am currently using Slope_MaxTriangle, SAGA_Wetness_Index, Catchment_Area, and Annual_Total Solar_Radiation as the terrain variables in the PCA/MLR work. 

However, the spreadsheet includes additional attributes (i.e., northness, eastness, standard TWI) that may also be of interest. 
Happy to answer any questions. 
Please let me know if any additional information should be added to the ReadMe file. 
-Rebecca
@rlybrand4

**Comment by noelleje** [comment]
Thanks @rlybrand4 , got the spreadsheet.
